[package]
name = "kafka-encode"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
integer-encoding = "3.0.4"
uuid = "1.2.2"
bytes = "1.3.0"
log = "0.4.17"
